// react-frontend/src/components/loginForm/LoginForm.tsx
import { useState } from 'react'
import { TextField, InputAdornment, IconButton } from '@mui/material'
import { LoadingButton } from '@mui/lab'
import { loginUser } from '../../utils/auth';
import { apiCall } from '../../utils/fetch';
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';
import { toStoreData } from '../../views/loginView/LoginView'
import './LoginForm.css'

interface loginData {
  email: string
  password: string
  uid?: string
}
interface loginFormProps {
  storeData: (data: toStoreData) => void
}
export default function LoginView({ storeData = (d) => {} }: loginFormProps) {
  const [password, setPassword] = useState('')
  const [email, setEmail] = useState('')
  const [emailErrorText, setEmailErrorText] = useState('')
  const [emailError, setEmailError] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [loading, setLoading] = useState(false)
  const validateEmail = () => {
    if(!(!!email)) {
      setEmailErrorText('E-mail is required')
      setEmailError(true)
      return false
    }
    if(!(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(email))) {
      setEmailErrorText('E-mail must be valid')
      setEmailError(true)
      return false
    }
    setEmailErrorText('')
    setEmailError(false)
    return true
  }
  const toggleShowPassword = () => {
    setShowPassword(!showPassword)
  }

  const login = async() => {
    try {
      const valid = validateEmail()
      if (!valid) return
      setLoading(true)
      let data : loginData = {
        email: email,
        password: password
      }
      const loginRes = await loginUser(data)
      data.uid = loginRes?.uid
      const dbRes = await apiCall('/login', 'POST', false, data)
      const toStore: toStoreData = {
        token: loginRes?.token,
        imageUrl: dbRes.imageUrl,
        expire: loginRes?.expirationTime,
        email: dbRes.email,
        alias: dbRes.alias
      }
      storeData(toStore)
      setLoading(false)
      // router.push('/')
    } catch (error) {
      // toastMessage.value = error
      // toastType.value = 'error'
      // toastActive.value = true
      // loading.value = false
    }
  }
  return (
    <div>
      <TextField fullWidth margin="dense" error={emailError} label="Email" variant="outlined" helperText={emailErrorText || ' '} value={email} onChange={(e) => {
          setEmail(e.target.value);
          validateEmail();
      }}/>
      <TextField fullWidth  type={showPassword ? 'text' : 'password'} label="Password" variant="outlined" value={password} onChange={(e) => {
          setPassword(e.target.value);
      }}
      InputProps={{
      endAdornment:
        <InputAdornment position="end">
          <IconButton
            onClick={toggleShowPassword}
            edge="end"
          >
            {showPassword ? <VisibilityOff /> : <Visibility />}
          </IconButton>
        </InputAdornment>
      }}
      />
      <LoadingButton fullWidth variant="contained" className='login-button' loading={loading} onClick={() =>login()}>Login</LoadingButton>
    </div>
  )
}

// frontend/src/components/LoginForm.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { apiCall } from '@/utils/fetch'
import { loginUser } from '@/utils/auth'

const emit = defineEmits(['storeData'])
const router = useRouter()
const toastMessage = ref('')
const toastType = ref('success')
const toastActive = ref(false)
const toastTimeout = 5000
const form = ref(null)
const password = ref('')
const email = ref('')
const loading = ref(false)
const hidePassword = ref(true)
const toggleHidePassword = () => {
	hidePassword.value = !hidePassword.value
}
const emailRules = ref([
	(v) => !!v || 'E-mail is required',
	(v) => /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(v) || 'E-mail must be valid' // eslint-disable-line no-useless-escape
])
const login = async() => {
	try {
		const { valid } = await form.value.validate()
		if (!valid) return
		loading.value = true
		const data = {
			email: email.value,
			password: password.value
		}
		const loginRes = await loginUser(data)
		data.uid = loginRes.uid
		const dbRes = await apiCall('/login', 'POST', false, data)
		const toStore = {
			token: loginRes.token,
			imageUrl: dbRes.imageUrl,
			expire: loginRes.expirationTime,
			email: dbRes.email,
			alias: dbRes.alias
		}
		loading.value = false
		emit('storeData', toStore)
		router.push('/')
	} catch (error) {
		toastMessage.value = error
		toastType.value = 'error'
		toastActive.value = true
		loading.value = false
	}
}
</script>
<template>
	<div>
		<v-container>
			<v-form ref="form">
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field variant="outlined" v-model="email" :rules="emailRules" label="Email" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field :type="hidePassword ? 'password' : 'text'" @click:append-inner="toggleHidePassword" :append-inner-icon="hidePassword ? 'mdi-eye' : 'mdi-eye-off'" variant="outlined" v-model="password" label="Password" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-btn @click="login()" :loading="loading" block color="secondary">Login</v-btn>
				</v-row>
			</v-form>
		</v-container>
		<v-snackbar :color="toastType" v-model="toastActive" :timeout="toastTimeout">{{ toastMessage }}</v-snackbar>
	</div>
</template>
