// react-frontend/src/components/signupForm/SignupForm.tsx
import { useMemo, useState } from 'react'
import { TextField } from '@mui/material'
import './SignupForm.css'
import { apiCall } from '../../utils/fetch'
import { registerUser } from '../../utils/auth'
import { LoadingButton } from '@mui/lab'
import { toStoreData } from '../../views/loginView/LoginView'
interface registerData {
  email: string
  password: string
  lastname: string
  name: string
  alias: string
  uid?: string
}

interface signupFormProps {
  storeData: (data: toStoreData) => void
}
export default function SignupView({ storeData = (d) => {} }: signupFormProps) {
  const [password, setPassword] = useState('')
  const [email, setEmail] = useState('')
  const [passwordConfirmation, setPasswordConfirmation] = useState('')
  const [name, setName] = useState('')
  const [lastName, setLastName] = useState('')
  const [alias, setAlias] = useState('')
  const [emailErrorText, setEmailErrorText] = useState('')
  const [emailError, setEmailError] = useState(false)
  const [passwordErrorText, setPasswordErrorText] = useState('')
  const [passwordError, setPasswordError] = useState(false)
  const [passwordConfirmationErrorText, setPasswordConfirmationErrorText] = useState('')
  const [passwordConfirmationError, setPasswordConfirmationError] = useState(false)
  const [nameErrorText, setNameErrorText] = useState('')
  const [nameError, setNameError] = useState(false)
  const [lastNameErrorText, setLastNameErrorText] = useState('')
  const [lastNameError, setLastNameError] = useState(false)
  const [aliasErrorText, setAliasErrorText] = useState('')
  const [aliasError, setAliasError] = useState(false)
  const [loading, setLoading] = useState(false)
  const [toastMessage, setToastMessage] = useState('')
  const [toastType, setToastType] = useState('success')
  const [toastActive, setToastActive] = useState(false)
  const [toastTimeout, setToastTimeout] = useState(5000)

  const validateEmail = () => {
    if(!(!!email)) {
      setEmailErrorText('E-mail is required')
      setEmailError(true)
      return false
    }
    if(!(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(email))) {
      setEmailErrorText('E-mail must be valid')
      setEmailError(true)
      return false
    }
    setEmailErrorText('')
    setEmailError(false)
    return true
  }

  const validatePassword = () => {
    if(!(!!password)) {
      setPasswordErrorText('Password is required')
      setPasswordError(true)
      return false
    }
    if(!(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}/.test(password))) {
      setPasswordErrorText('Must have 8 characters, uppercase, number')
      setPasswordError(true)
      return false
    }
    setPasswordErrorText('')
    setPasswordError(false)
    return true
  }

  const validatePasswordConfirmation = useMemo(() => {
    if(password === passwordConfirmation) {
      setPasswordConfirmationError(false)
      setPasswordConfirmationErrorText('')
      return true
    }
    setPasswordConfirmationErrorText('Passwords must match')
    setPasswordConfirmationError(true)
    return false
  }, [password, passwordConfirmation])

  const validateName = () => {
    if(!(!!name)) {
      setNameErrorText('Name is required')
      setNameError(true)
      return false
    }
    setNameErrorText('')
    setNameError(false)
    return true
  }

  const validateLastName = () => {
    if(!(!!lastName)) {
      setLastNameErrorText('Last Name is required')
      setLastNameError(true)
      return false
    }
    setLastNameErrorText('')
    setLastNameError(false)
    return true
  }

  const validateAlias = () => {
    if(!(!!alias)) {
      setAliasErrorText('Alias is required')
      setAliasError(true)
      return false
    }
    if(!(alias.length > 3)) {
      setAliasErrorText('Alias must be at least 4 characters long')
      setAliasError(true)
      return false
    }
    setAliasErrorText('')
    setAliasError(false)
    return true
  }

  const signup = async() => {
    try {
      const valid = validateEmail() && validatePassword() && validatePasswordConfirmation && validateName() && validateLastName() && validateAlias()
      if (!valid) return

      setLoading(true)
      const aliasFoundRes = await apiCall(`/alias/${alias}`, 'GET', false)
      console.log(aliasFoundRes)
      if (aliasFoundRes.aliasFound) {
        setToastMessage('Alias already in use')
        setToastType('error')
        setToastActive(true)
        setLoading(false)
        return
      }
      const data: registerData = {
        email: email,
        password: password,
        lastname: lastName,
        name: name,
        alias: alias
      }
      const registerRes = await registerUser(data)
      data.uid = registerRes?.uid
      const dbRes = await apiCall('/signup', 'POST', false, data)
      const toStore: toStoreData = {
        token: registerRes?.token,
        imageUrl: dbRes.imageUrl,
        expire: registerRes?.expirationTime,
        email: dbRes.email,
        alias: dbRes.alias
      }
      setLoading(false)
      storeData(toStore)
      // // router.push('/')
    } catch (error) {
      setLoading(false)
      setToastMessage(error as string)
      setToastType('error')
      setToastActive(true)
    }
  }

  return (
    <div>
      <TextField fullWidth error={emailError} className='email-field' label="Email" variant="outlined" helperText={emailErrorText || ' '} value={email} onChange={(e) => {
          setEmail(e.target.value);
          validateEmail();
      }}/>
      <TextField fullWidth type='password' error={passwordError} label="Password" variant="outlined" helperText={passwordErrorText || ' '} value={password} onChange={(e) => {
          setPassword(e.target.value);
          validatePassword();
      }}/>
      <TextField fullWidth type='password' error={passwordConfirmationError} label="Password Confirmation" variant="outlined" helperText={passwordConfirmationErrorText || ' '} value={passwordConfirmation} onChange={(e) => {
          setPasswordConfirmation(e.target.value);
      }}/>
      <TextField fullWidth error={nameError} label="Name" variant="outlined" helperText={ nameErrorText ||`${name.length}/20`} value={name} onChange={(e) => {
          setName(e.target.value);
          validateName();
        }}
        inputProps={{
          maxLength: 20
      }}/>
      <TextField fullWidth error={lastNameError} label="Last Name" variant="outlined" helperText={ lastNameErrorText ||`${lastName.length}/20`} value={lastName} onChange={(e) => {
          setLastName(e.target.value);
          validateLastName();
        }}
        inputProps={{
          maxLength: 20
      }}/>
      <TextField fullWidth error={aliasError} label="Alias/Pen Name" variant="outlined" helperText={ aliasErrorText ||`${alias.length}/25`} value={alias} onChange={(e) => {
          setAlias(e.target.value);
          validateAlias();
        }}
        inputProps={{
          maxLength: 25
      }}/>
      <LoadingButton fullWidth variant="contained" className='signup-button' onClick={() => signup()} loading={loading}>Sign Up</LoadingButton>
    </div>
  )
}

// frontend/src/components/SignupForm.vue
<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { apiCall } from '@/utils/fetch'
import { registerUser } from '@/utils/auth'
const router = useRouter()
const emit = defineEmits(['storeData'])
const form = ref(null)

const name = ref('')
const lastName = ref('')
const password = ref('')
const confirmPassword = ref('')
const email = ref('')
const alias = ref('')
const toastMessage = ref('')
const toastType = ref('success')
const toastActive = ref(false)
const toastTimeout = 5000
const loading = ref(false)
const emailRules = ref([
	(v) => !!v || 'E-mail is required',
	(v) => /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(v) || 'E-mail must be valid' // eslint-disable-line no-useless-escape
])
const passwordRules = ref([
	(v) => !!v || 'Password is required',
	(v) => /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}/.test(v) || 'Password must have at least 8 characters, one uppercase letter and one number'
])
const passwordConfirmationRules = ref([
	(v) => !!v || 'Password Confirmation is required'
])
const nameRules = ref([
	(v) => !!v || 'Name is required',
	(v) => v.length < 21 || 'Name cannot be longer than 20 characters'
])
const lastNameRules = ref([
	(v) => !!v || 'Last Name is required',
	(v) => v.length < 21 || 'Last Name cannot be longer than 20 characters'
])
const aliasRules = ref([
	(v) => !!v || 'Pen Name is required',
	(v) => v.length > 3 || 'Alias must be at least 4 characters long',
	(v) => v.length < 26 || 'Alias cannot be longer than 25 characters'
])
const passwordConfirmationRule = computed(()=> {
	return () => (password.value === confirmPassword.value) || 'Password must match'
})
const signup = async() => {
	try {
		const { valid } = await form.value.validate()
		if (!valid) return
		loading.value = true
		const aliasFoundRes = await apiCall(`/alias/${alias.value}`, 'GET', false)
		if (aliasFoundRes.aliasFound) {
			toastMessage.value = 'Alias already in use'
			toastType.value = 'error'
			toastActive.value = true
			loading.value = false
			return
		}
		const data = {
			email: email.value,
			password: password.value,
			lastname: lastName.value,
			name: name.value,
			alias: alias.value
		}
		const registerRes = await registerUser(data)
		data.uid = registerRes.uid
		const dbRes = await apiCall('/signup', 'POST', false, data)
		const toStore = {
			token: registerRes.token,
			imageUrl: dbRes.imageUrl,
			expire: registerRes.expirationTime,
			email: dbRes.email,
			alias: dbRes.alias
		}
		loading.value = false
		emit('storeData', toStore)
		router.push('/')
	} catch (error) {
		loading.value = false
		toastMessage.value = error
		toastType.value = 'error'
		toastActive.value = true
	}
}
</script>

<template>
	<div>
		<v-form ref="form">
			<v-container>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field variant="outlined" v-model="email" :rules="emailRules" label="Email" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field variant="outlined" type="password" v-model="password" label="Password" :rules="passwordRules" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field variant="outlined" type="password" v-model="confirmPassword" :rules="passwordConfirmationRules.concat(passwordConfirmationRule)" label="Password Confirmation" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field counter="20" variant="outlined" v-model="name" label="Name" :rules="nameRules" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field counter="20" variant="outlined" v-model="lastName" label="Last Name" :rules="lastNameRules" required>
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-col cols="12">
						<v-text-field counter="25" variant="outlined" v-model="alias" label="Pen Name/Alias" :rules="aliasRules" required hint="Unique display name, cannot be changed">
						</v-text-field>
					</v-col>
				</v-row>
				<v-row no-gutters>
					<v-btn block :loading="loading" color="secondary" @click="signup()">Sign Up</v-btn>
				</v-row>
			</v-container>
		</v-form>
		<v-snackbar :color="toastType" v-model="toastActive" :timeout="toastTimeout">{{ toastMessage }}</v-snackbar>
	</div>
</template>
