// react-frontend/src/views/loginView/LoginView.tsx
import { useState } from 'react'
import './LoginView.css'
import { Grid, Box, Card, CardContent, Divider, Button } from '@mui/material'
import Carousel from 'react-material-ui-carousel'
import LoginForm from '../../components/loginForm/LoginForm'
import SignupForm from '../../components/signupForm/SignupForm'
import {loginTexts} from '../../utils/texts'
import spLogo from './../../assets/spLogo.svg'
import { useAppDispatch } from './../../hooks'
import { setToken, setTokenExpirationDate } from '../../features/token/tokenSlice'
import { setImage, setUserAlias, setUserEmail } from '../../features/user/userSlice'


export interface toStoreData  {
  token?: string
  imageUrl: string
  expire?: string
  email: string
  alias: string
}

function LoginView() {
  const [phase, setPhase] = useState(0)
  const dispatch = useAppDispatch()
  const storeData = (data: toStoreData) => {
    if(data.token != undefined) {
      dispatch(setToken({token: data.token}))
    }
    if(data.expire != undefined) {
      dispatch(setTokenExpirationDate({tokenExpirationDate: data.expire}))
    }
    dispatch(setImage({profileImage: data.imageUrl}))
    dispatch(setUserAlias({userAlias: data.alias}))
    dispatch(setUserEmail({userEmail: data.email}))
  }

  return (
    <div className='view-height'>
      <Box className='full-height'>
        <Grid container className='full-height'>
          <Grid item xs={6} display="flex" justifyContent="center" alignItems="center">
            <div>
              <img src={spLogo} alt="SpeakPoet Logo" width="400" height="150" style={{objectFit: 'cover'}}/>
              <Carousel swipe={false} interval={8000} animation='slide' navButtonsAlwaysInvisible 
                indicatorContainerProps={{ style: { visibility: 'hidden' }}}>
                { loginTexts().map( (item, i) => <h2 key={i}>{item}</h2> ) }
              </Carousel>
            </div>
          </Grid>
          <Grid item xs={6} display="flex" justifyContent="center" alignItems="center">
            <Card variant="outlined" className={phase == 1 ? 'signup-card' : 'login-card'}>
              <CardContent>
                <Carousel swipe={false} animation='slide' navButtonsAlwaysInvisible indicators={false} autoPlay={false} index={phase}>
                  <div>
                    <LoginForm storeData={ storeData }></LoginForm>
                    <Divider className="divider"/>
                    <Button fullWidth variant="contained" className='login-button' onClick={() => setPhase(1)} color="success">Sign Up</Button>
                  </div>
                  <div>
                    <SignupForm storeData={ storeData }></SignupForm>
                    <Divider className="divider"/>
                    <Button fullWidth variant="contained" className='login-button' onClick={() => setPhase(0)} color="success">Have an account? Login</Button>
                  </div>
                </Carousel>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </Box>
    </div>
  )
}

export default LoginView

// frontend/src/views/LoginView.vue
<script setup>
import { useAppStore } from './../store/app'
import { ref } from 'vue'
import LoginForm from '../components/LoginForm.vue'
import SignupForm from '../components/SignupForm.vue'
import { loginTexts } from './../utils/texts'
const store = useAppStore()
const loginPhase = ref(true)
const phase = ref('0')
const signupPhase = () => {
	loginPhase.value = false
	phase.value = '1'
}
const returnToLoginPhase = () => {
	loginPhase.value = true
	phase.value = '0'
}
const storeData = (obj) => {
	store.setToken(obj.token)
	store.setImage(obj.imageUrl)
	store.setTokenExpirationDate(obj.expire)
	store.setUserAlias(obj.alias)
	store.setUserEmail(obj.email)
}
</script>

<template>
	<v-container class="container">
		<v-row align="center" class="rows">
			<v-col>
				<v-row align="center" class="rows" no-gutters justify="center">
					<div class="text-container">
						<div class="pl-5">
							<v-img
							width="400"
							height="150"
							src="@/assets/spLogo.svg"
							cover
							></v-img>
						</div>
						<v-carousel height=150 interval=8000 hide-delimiters cycle :show-arrows="false">
							<v-carousel-item v-for="(quote, i) in loginTexts()" :key="i">
								<h2>{{ quote }}</h2>
							</v-carousel-item>
						</v-carousel>
					</div>
				</v-row>
			</v-col>
			<v-col>
				<v-row align="end" class="rows" no-gutters justify="center">
					<v-carousel :show-arrows="false" hide-delimiters v-model="phase" class="carousel">
						<v-carousel-item value='0'>
							<v-card elevation="2" outlined width="400px" transition="slide-x-reverse-transition" >
								<login-form @store-data="storeData"/>
								<v-divider></v-divider>
								<v-container>
									<v-btn block color="success" @click="signupPhase()">Sign Up</v-btn>
								</v-container>
							</v-card>
						</v-carousel-item>
						<v-carousel-item value='1'>
							<v-card elevation="2" outlined width="400px" transition="slide-x-reverse-transition" >
								<signup-form @store-data="storeData"/>
								<v-divider></v-divider>
								<v-container>
									<v-btn block color="success" @click="returnToLoginPhase()">Have an account? Login</v-btn>
								</v-container>
							</v-card>
						</v-carousel-item>
					</v-carousel>
				</v-row>
			</v-col>
		</v-row>
	</v-container>
</template>
<style scoped>
.container {
	height: 80%;
}
.rows {
	height: 100%;
}
.text-container {
	width: 500px;
}
.text-title {
	padding-bottom: 10px;
}
.carousel {
	height: inherit !important;
	width: inherit !important;
}
</style>
